package com.pushwoosh.reactnativeplugin;

import com.facebook.react.bridge.ReactApplicationContext;

// New Architecture: NativePushwooshSpec is generated by codegen from src/specs/NativePushwoosh.ts.
abstract class PushwooshPluginSpec extends NativePushwooshSpec {
	PushwooshPluginSpec(ReactApplicationContext reactContext) {
		super(reactContext);
	}
}
